### ISSUE TITLE
How can I  manually promote.

### ISSUE THREAD

**Issue by WillStreeter** [lykmapipo/sails-hook-subscriber#1]
Hi,

I am just giving your pub/sub a  go here.  When I publish.create(), it correctly is pushed in redis and then loaded  with subscriber after 5 seconds. It works great. I was wondering if it is possible to introduce a delay. If whatever reason the Job is not ready to be promoted, how can I  manually promote(). Even better if I a manual promote can use the subscriber Worker that has been created...

Thanks
P.S. Great Job BTW
Will

**Comment by lykmapipo** [comment]
@WillStreeter 

Since [sails-hook-subscriber](https://github.com/lykmapipo/sails-hook-subscriber) based on [Kue](https://github.com/learnboost/kue):

**I was wondering if it is possible to introduce a delay?**
- For delayed jobs you may take a look on [Kue Delayed Job](https://github.com/learnboost/kue#delayed-jobs)

**If whatever reason the Job is not ready to be promoted, how can I manually promote()?**
- [sails-hook-subsciber](https://github.com/lykmapipo/sails-hook-subscriber) use [kue](https://github.com/learnboost/kue) recommendation of just calling `promote()` once, [see](https://github.com/lykmapipo/sails-hook-subscriber/blob/master/index.js#L88), which I think is a best practise relating to delayed jobs and job promotion.

**Even better if I a manual promote can use the subscriber Worker that has been created?**
- So far [sails-hook-subscriber]() does not cache worker(s), [see](https://github.com/lykmapipo/sails-hook-subscriber/blob/master/index.js#L122). All it does is to wire up your worker(s) to [kue](https://github.com/learnboost/kue). 

Hope this is helping.
